services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    env_file:
      - .env.development
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  minio:
    container_name: minio
    image: minio/minio
    command: server /data --console-address ":9001"
    env_file:
      - .env.development
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
      - '9000:${MINIO_CONSOLE_PORT}'
      - '9001:${MINIO_PORT}'
    volumes:
      - minio_data:/data

  minio-client:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      sh -c "
        sleep 5 &&
        mc alias set local http://minio:${MINIO_PORT} ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY} &&
        mc mb -p local/${MINIO_BUCKET_NAME} || true &&
        mc anonymous set public local/${MINIO_BUCKET_NAME}
      "

volumes:
  postgres_data:
  minio_data:

networks:
  backend:
